-- AlterTable
ALTER TABLE `properties` MODIFY `status` ENUM('VENDIDO', 'LOCADO', 'SUSPENSO', 'ATIVO') NOT NULL DEFAULT 'ATIVO',
    MODIFY `type_structure` ENUM('CONDOMINIO', 'EDIFICIO', 'RESIDENCIAL') NOT NULL DEFAULT 'RESIDENCIAL',
    MODIFY `suites` INTEGER NULL DEFAULT 0,
    MODIFY `parking_spaces` INTEGER NULL DEFAULT 0,
    MODIFY `total_area` DOUBLE NULL DEFAULT 0,
    MODIFY `building_area` DOUBLE NULL DEFAULT 0,
    MODIFY `land_area` DOUBLE NULL DEFAULT 0;
